[project]
name = "umt-pythonweb-hw-08"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "bcrypt<5.0.0",
    "cloudinary>=1.44.2",
    "fastapi-mail>=1.6.4",
    "fastapi[standard]>=0.136.3",
    "passlib[bcrypt]>=1.7.4",
    "phonenumbers>=9.0.31",
    "pydantic-extra-types>=2.11.1",
    "pydantic-settings>=2.14.1",
    "python-jose[cryptography]>=3.5.0",
    "redis>=8.0.1",
    "slowapi>=0.1.9",
    "sphinx>=9.1.0",
    "sqlalchemy>=2.0.50",
]

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
pythonpath = "."
