"""add_role_column

Revision ID: 3131036d2154
Revises: 65e76daf9a2c
Create Date: 2026-07-11 02:44:25.387359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3131036d2154'
down_revision: Union[str, Sequence[str], None] = '65e76daf9a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_type = sa.Enum('USER', 'ADMIN', name='role')
    role_type.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', role_type, nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    role_type = sa.Enum('USER', 'ADMIN', name='role')
    role_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
